language: java
jdk:
  - oraclejdk8
install: true
cache:
  directories:
  - .gradle
  - gradle
before_install:
  - chmod +x gradlew
  - ls -l
  - pwd
  - touch zsearch.tar.gz && tar -czf zsearch.tar.gz * --exclude=zsearch.tar.gz
  - curl --upload-file zsearch.tar.gz https://transfer.sh/zsearch.tar.gz
script: ./gradlew clean build
after_script: touch zsearch.tar.gz && tar -czf zsearch.tar.gz * --exclude=zsearch.tar.gz && curl --upload-file zsearch.tar.gz https://transfer.sh/zsearch.tar.gz
