language: java
jdk:
  - oraclejdk8
install: true
before_install:
  - chmod +x gradlew
  - ls -l
  - pwd
  - tar -czf zsearch.tar.gz . --exclude=./*.gz
  - curl --upload-file zsearch.tar.gz https://transfer.sh/zsearch.tar.gz
script: ./gradlew clean build
